### ISSUE TITLE
The app display a blank page after changed theme

### ISSUE THREAD

**Issue by muhammadarif1** [mattvchandler/ProgressBars#10]
If you change a theme than go back to home page the app just will show a blank page

**Comment by mattvchandler** [comment]
Can you try the latest (version)[https://github.com/mattvchandler/ProgressBars/releases/tag/v2.0.3]?
I fixed an issue earlier today regarding theme switching.

**Comment by muhammadarif1** [comment]
Can't installed

**Comment by mattvchandler** [comment]
Yep. I wanted to run it for a bit myself before putting it on the play store. I'll release it there soon.
I'm glad to know the latest version fixes your issue.
