### ISSUE TITLE
ProgressBars v2.0.3 - The "Notification Settings" feature in the Add new timer section cannot be used.

### ISSUE THREAD

**Issue by ammarraisafti** [mattvchandler/ProgressBars#11]
# Actual behaviour
When adding a new timer.  The ability to access the "Notification Settings" feature available in it should be able to be done.

# Expected behaviour
The "Notification Settings" feature in the Add new timer section should be accessed or used.

# Step to reproduce
- Install the application, open and run the application.

- Click the add icon at the top to add a new timer.

- Scroll down, click on the "Notification Settings" feature.

- Then you will find problems like I have experienced.

# Information
- App version: 2.0.3
- Android version: 8.0
- Browser: Asus zenfone 3 

# Recording of the bug
https://youtu.be/R58ZGutP_Ms

**Comment by mattvchandler** [comment]
I see that too on 8.0, and I've got a good idea of what's wrong

https://github.com/mattvchandler/ProgressBars/blob/79e4f004ac3ba841f59c9eaf7ef4f9266ae1d74c/app/src/main/java/settings/Settings.kt#L608

This, and a few other places, should be '>= 26'

Let me do some testing to make sure I get them all, and I'll get a patch released

**Comment by mattvchandler** [comment]
That should fix it. The new version is available  [here](https://github.com/mattvchandler/ProgressBars/releases/tag/v2.0.4), and should be appearing in play store and fdroid soon.
