### ISSUE TITLE
[feature request] Setting first day of week

### ISSUE THREAD

**Issue by jonfre** [mattvchandler/ProgressBars#14]
Setting for first day of week to affect date pickers. The system language does not necessarily correspont to what the user wants.

**Comment by mattvchandler** [comment]
Sounds reasonable.

**Comment by jonfre** [comment]
I'll try to do a PR for this later

**Comment by mattvchandler** [comment]
Added in version [2.0.5](https://github.com/mattvchandler/ProgressBars/releases/tag/v2.0.4)
