### ISSUE TITLE
Android 13 - can't add widget to desktop

### ISSUE THREAD

**Issue by osowiecki** [mattvchandler/ProgressBars#27]
ADW launcher claims that the app is not installed. Can't add the widget to the Desktop.

**Comment by mattvchandler** [comment]
You might want to take that up with your launcher app. I'm not doing anything weird that should cause that sort of behavior in this app, and it works fine in the half-dozen or so launchers I've used it on over the years.
I'm going to close this issue for now, but if the ADW launcher devs can point out something that needs fixing on my end, feel free to add this here.
