### ISSUE TITLE
new feature - ask before swiping bar away

### ISSUE THREAD

**Issue by osowiecki** [mattvchandler/ProgressBars#28]
i often swipe the progress bar away by accident. Can you add a confirmation button before you delete the counter?

**Comment by mattvchandler** [comment]
I'm not looking to add much in the way of new features to this app.
Also, adding a confirmation doesn't match the typical usage of swipe-to- delete. In gmail, for example, you don't have to confirm archiving a message. It does put a snackbar up with an undo button, but this app already has an undo button at the top, so I consider that redundant.
If you submit a PR adding a similar snackbar-based button, I'll probably merge it, though.
