### ISSUE TITLE
[BUG?] widgets are not picking up the bars that have been already created; it creates a new one

### ISSUE THREAD

**Issue by formula-spectre** [mattvchandler/ProgressBars#29]
I don't know if it's a bug or a feature ™️; but when I try to add a widget it makes me create a new countdown bar, not choose from the ones I already have created in app. is this intended?

**Comment by mattvchandler** [comment]
It's intentional. Widget timers are just stored / handled separately from timers in the app. I had thought about tying them together somehow, but I couldn't decide on a good way to do it.

**Comment by formula-spectre** [comment]
gotcha!
since you already closed the issue, can I ask an OT question? I want to make a progress bar that tracks the week, but I find it kinda confusing; which repeat should I use?

**Comment by mattvchandler** [comment]
You probably want it to repeat every 7 days to track the week itself.
The week repeat settings are for when you want to have something on a
specific day or days of the week. For example, I have work every weekday
8-5, and I have a timer set to repeat every 1 week on MTWRF

**Comment by kpcenti** [comment]
Is there any reason to have them separate? 

It seems odd to have the user have to rebuild the timer they want again for a widget if they already have everything configured in the app. 

It also becomes cumbersome having to edit the app timer and the widget timer. At the moment the you can only edit the the most recently built Widget. 

Other similar apps like Clock and Calendar have the app instance as the source and the widget pulls from that.
