### ISSUE TITLE
Put the "Undo" button inside the three-dots.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [mattvchandler/ProgressBars#30]
Bro, can you quickly put the "Undo" button inside the three-dots?

Apart from that, I have no requests.

Thanks!

**Comment by mattvchandler** [comment]
I like the button where it is, but if you'd like to move it for yourself, you'd only need to change this line:
https://github.com/mattvchandler/ProgressBars/blob/f2c430c9672b8f932e6abba9fbce51e496697dc9/app/src/main/res/menu/progress_bar_action_bar.xml#L37
and probably line 42 as well to "never"

**Comment by Aryan-Chauhan** [comment]
> I like the button where it is, but if you'd like to move it for yourself, you'd only need to change this line:
> https://github.com/mattvchandler/ProgressBars/blob/f2c430c9672b8f932e6abba9fbce51e496697dc9/app/src/main/res/menu/progress_bar_action_bar.xml#L37
> and probably line 42 as well to "never"
> 

Thanks!
