### ISSUE TITLE
Repeat options

### ISSUE THREAD

**Issue by pudah** [mattvchandler/ProgressBars#31]
Would it be possible to allow for "weekdays" as an option when configuring the Repeat setting?

**Comment by mattvchandler** [comment]
You can already select individual days when repeating weekly. Just select Monday through Friday to have it repeat on weekdays

![](https://i.imgur.com/PnoRw00.png)

![](https://i.imgur.com/Kwcajdb.png)

**Comment by pudah** [comment]
I didn't even think to check under weekly. Thanks for the tip!
