### ISSUE TITLE
Add app widget

### ISSUE THREAD

**Issue by mattvchandler** [mattvchandler/ProgressBars#8]
Add option for an app widget

* Verify that battery usage isn't significant
* How quickly can the widget be refreshed?

**Comment by 7596ff** [comment]
I'd love this feature.

**Comment by JoshGate17** [comment]
Any update on this feature progression work?

**Comment by mattvchandler** [comment]
I have a partially working prototype on my phone. Currently, it has issues where it stops updating or stops responding to touches. I think this may be related to power saving killing the process.

That being said, I haven't had time to work on this in the last couple of months. Life has been pretty busy lately. I still intend to finish this feature and others, but it could be a while.

Thank you for your enthusiasm. This should be a really nice feature once it's ready.

**Comment by brownianmotion** [comment]
Hi Matt, any chance you could check in what you've got so far on a branch? I just came across ProgressBars in F-Droid while looking for a countdown widget, and figured I'd offer some help.

**Comment by mattvchandler** [comment]
Give me a bit to clean it up a bit.

**Comment by mattvchandler** [comment]
Added in [v2.1.1](https://github.com/mattvchandler/ProgressBars/releases/tag/v2.1.1)

**Comment by Aq32** [comment]
Hi. Not sure if I should start a new topic but some thoughts:
- Needs confirmation by someone else but if you add more than one ProgressBar Widget (I tested with two) the first one doesn't work. By doesn't work you can only tap and edit the last widget.
- Include an option to resize the spacing between the text in the widget or make a compact widget and the current one to use less grid space.
- Could allow the user to customise the colours including fonts and background fill of the widget and transparency.

An alternative or complementary idea:
- A new type of widget that can be stretched to a whole page (or just larger) that shows multiple existing in app ProgressBar timers. Not sure if the widget versions of ProgressBar are meant to be separate/distinct from the main app ProgressBars timers.

Anyway, good work on this project so far and seeing the other issues and suggestions I'm looking forward to the future improvements!

**Comment by mattvchandler** [comment]
Yes, please open this in a new issue, or even better, put the bug into a separate issue from the feature requests

**Comment by Aq32** [comment]
In hindsight that was the better idea! New issues created and should be better explained too.
