### ISSUE TITLE
[Bug] App fails to respond to any command after theme is changed

### ISSUE THREAD

**Issue by jubreal** [mattvchandler/ProgressBars#9]
#### Expected behavior
The app should respond to users touch and command.

#### Actual behavior
The app fails to respond to the command or user's click on buttons after the theme was changed.

#### How To Reproduce
1 Click on the menu button (3 horizontal dots at the top right corner)
2 Click on settings
3 Click on "Day / Night Theme" option
4 Select "Night", and then go back to the home page
5 Try clicking on any of the icons, you'll notice that the app fails to respond to this.

Device
Android 6.0
App Version 2.0.2

#### Screen Recording
https://youtu.be/Oc1Kr1xEwV0

**Comment by mattvchandler** [comment]
I'm not seeing this one.
Can you double check the version number? Looks like copy/paste from your report in 2050. This app never had a 1.0.5.
2050 and ProgressBars both use the same theming code, so once I find a fix there (mattvchandler/2050#5), I might be able to apply it here and see if that fixes things for you.

**Comment by jubreal** [comment]
Yes, I noticed they used the same theming code, that was why I tried checking if it triggers any bug in this app too. Sorry for the mistake in the app version. It is fixed now.

**Comment by mattvchandler** [comment]
Can you try [v2.0.3](https://github.com/mattvchandler/ProgressBars/releases/tag/v2.0.3)? I wasn't able to reproduce the freezing issue myself, but I did see an exception being thrown and was able to fix that.

**Comment by jubreal** [comment]
It works perfectly now. Thanks
I'll close the issue now

**Comment by mattvchandler** [comment]
Thank you for catching & reporting this.
